### ISSUE TITLE
Move to ES6 and use babel

### ISSUE THREAD

**Issue by svens-uk** [Kurimizumi/Honeybee-Web#3]
After #2, we should integrate babel into the bundling process, as it would make it easier to keep the web version up to date with the node version.

**Comment by ethan-dorta** [comment]
Give me two seconds.

**Comment by ethan-dorta** [comment]
Done!

**Comment by ethan-dorta** [comment]
UglifyJS will break if ES6 code is put in, I'm gonna fix that right now.
